export const INIT_APP = 'INIT_APP';
export const GET_CURRENT_NETWORK = 'GET_CURRENT_NETWORK';
export const GET_USD_PRICE = 'GET_USD_PRICE';
export const BIRTH_KAIJUS = 'BIRTH_KAIJUS';
export const FIND_KAIJUS_BY_TOKEN_ID = 'FIND_KAIJUS_BY_TOKEN_ID';
export const FIND_KAIJUS_BY_NFC_ID = 'FIND_KAIJUS_BY_NFC_ID';
export const LOAD_ACCOUNT_KAIJUS = 'LOAD_ACCOUNT_KAIJUS';
export const LOAD_ALL_KAIJUS = 'LOAD_ALL_KAIJUS';
