export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_CURRENT_NETWORK = 'SET_CURRENT_NETWORK';
export const SET_ETHERSCAN_NETWORK = 'SET_ETHERSCAN_NETWORK';
export const SET_USD_PRICE = 'SET_USD_PRICE';
export const SET_WEB3 = 'SET_WEB3';

export const SET_KAIJUS_UPLOAD_HASH = 'SET_KAIJUS_UPLOAD_HASH';
export const SET_KAIJUS_TOTAL_SUPPLY = 'SET_KAIJUS_TOTAL_SUPPLY';
export const SET_KAIJUS_SEARCH = 'SET_KAIJUS_SEARCH';
export const SET_ACCOUNT_KAIJUS = 'SET_ACCOUNT_KAIJUS';
export const SET_ALL_KAIJUS = 'SET_ALL_KAIJUS';
export const SET_KAIJUS_SEARCH_NOT_FOUND = 'SET_KAIJUS_SEARCH_NOT_FOUND';
export const SET_TRANSFER = 'SET_TRANSFER';
